using UnityEngine;

public class BagasDialogue : MonoBehaviour
{
    public DialogueManager dialogueManager;

    void Start()
    {
        DialogueData[] data =
        {
            new DialogueData(true, "Bagas?"),
            new DialogueData(false, "Siape lu?"),
            new DialogueData(true, "Dani. Penyidik."),
            new DialogueData(false, "Oh. Polisi. Terus?"),
            new DialogueData(true, "Saya ingin bertanya soal Binar."),
            new DialogueData(false, "Bertanya mulu dah. Dari tadi orang pada nyari gue."),
            new DialogueData(true, "Ya kalau tidak keberatan, saya mulai."),
            new DialogueData(false, "Kalau keberatan gimane?"),
            new DialogueData(true, "Saya tetap bertanya."),
            new DialogueData(false, "Nah tuh. Sama aja boong lu nanya. Apaan coba?"),
            new DialogueData(true, "..."),
            new DialogueData(false, "Kenape lu?"),
            new DialogueData(true, "Enggak. Cuma heran aja lu masih bisa ngomong sebanyak itu tanpa menjawab satu pertanyaan pun."),
            new DialogueData(false, "Buset. Polisi sekarang mulutnye pedes juga."),
            new DialogueData(true, "Tergantung yang diajak ngomong."),
            new DialogueData(false, "Oke dah. Tanya ape."),
            new DialogueData(true, "Lu sering datang ke kontrakan Binar."),
            new DialogueData(false, "Iye. Terus kenape?"),
            new DialogueData(true, "Ngapain?"),
            new DialogueData(false, "Nagih duit keamanan."),
            new DialogueData(true, "Pungli kali maksud lu."),
            new DialogueData(false, "Bahasanye jangan tinggi-tinggi dah, Bang."),
            new DialogueData(true, "Ya lu aman dari kasus ini tapi ntar di tahan gara-gara pungli kalo gitu. Keren lu begitu?"),
            new DialogueData(false, "Ya tanya aja warga lain, gue biasa begini kali."),
            new DialogueData(true, "Eh lu yang sopan selagi bahasa gue masih sopan."),
            new DialogueData(false, "Iye dah, iye."),
            new DialogueData(true, "Lu gue urus nanti ye, awas lu."),
            new DialogueData(true, "Hubungan lu sama Binar gimana?"),
            new DialogueData(false, "Berantem mulu."),
            new DialogueData(true, "Karena?"),
            new DialogueData(false, "Karena tuh cewek kaga pernah takut sama gue."),
            new DialogueData(true, "Kasian juga ya."),
            new DialogueData(false, "Apanye yang kasian?"),
            new DialogueData(true, "Preman ditakutin bocah SMP aja belum tentu, apalagi sama Binar."),
            new DialogueData(false, "Eh jangan ngelunjak lu."),
            new DialogueData(true, "Ya jawab yang bener kalau gak mau gue sindir terus."),
            new DialogueData(false, "Ya kalo gue tau gue jawab."),
            new DialogueData(true, "Menurut CCTV lu pernah ditendang dia."),
            new DialogueData(false, "Nah tuh. Lu liat sendiri kan."),
            new DialogueData(true, "Kenapa ditendang?"),
            new DialogueData(false, "Gue ngetok pintu agak keras."),
            new DialogueData(true, "Agak keras?"),
            new DialogueData(false, "Ya mungkin keras dikit."),
            new DialogueData(true, "Terus dia keluar dan nendang lu."),
            new DialogueData(false, "E bujung nanya mulu. Ya iye lah."),
            new DialogueData(true, "Dan lu diem aja?"),
            new DialogueData(false, "Emang gue harus mukul cewek?"),
            new DialogueData(true, "Gue cuma memastikan."),
            new DialogueData(false, "Lu mah nyari ribut."),
            new DialogueData(true, "Lu yang dari awal nyolot."),
            new DialogueData(false, "Yaudah gue pergi nih."),
            new DialogueData(true, "Pernah ada momen lu ngobrol baik-baik sama Binar?"),
            new DialogueData(false, "Pernah sekali."),
            new DialogueData(true, "Kapan?"),
            new DialogueData(false, "Motornye mogok di perempatan depan. 3 hari lalu."),
            new DialogueData(false, "Inget banget gue soalnya itu Senin."),
            new DialogueData(true, "Terus?"),
            new DialogueData(false, "Dia minta tolong gue dorongin ke bengkel kampung."),
            new DialogueData(true, "Lu bantu?"),
            new DialogueData(false, "Ya gue bantu lah. Masa gue tinggal."),
            new DialogueData(true, "Ajaib juga."),
            new DialogueData(false, "Ajaib pala lu."),
            new DialogueData(true, "Lanjut."),
            new DialogueData(false, "Sepanjang jalan dia masih ngomel-ngomel."),
            new DialogueData(false, "Katanye jalanan rusak lah, motor jelek, hidup susah lah. Macem-macem dah. Sampe pejabat-pejabat korup juga die katain."),
            new DialogueData(true, "Tetap konsisten ya."),
            new DialogueData(true, "Spesifik pejabatnya siapa?"),
            new DialogueData(false, "Nah itu. Mulutnye kaga bisa diem."),
            new DialogueData(false, "Gue lupa siapa, kayaknya yang korup baru-baru ini, si Baskoro Baskoro itu."),
            new DialogueData(true, "Setelah sampai bengkel?"),
            new DialogueData(false, "Gue tawarin anter pulang."),
            new DialogueData(true, "Terus?"),
            new DialogueData(false, "Ditolak lah kocak."),
            new DialogueData(false, "Katanye udah nelpon temennye, temen cewek."),
            new DialogueData(true, "Sering datang ke kontrakan?"),
            new DialogueData(false, "Kagak. Jarang banget."),
            new DialogueData(false, "Yang bikin gue heran, tuh orang berangkat dari Depok."),
            new DialogueData(true, "Depok?"),
            new DialogueData(false, "Iye. Jauh-jauh dari Depok cuma buat jemput dia."),
            new DialogueData(true, "Padahal lu udah nawarin bantuan."),
            new DialogueData(false, "Makanye. Orang waras mana begitu."),
            new DialogueData(true, "Jadi menurut lu Binar orang yang kepala batu."),
            new DialogueData(false, "Udah kepala batu, kaga kenal takut, sama rada gile."),
            new DialogueData(false, "Gue aja dilawan terus. Lu pikir dia takut sama orang lain?"),
            new DialogueData(true, "Takut Tuhan kali. Yaudah, itu aja dulu."),
            new DialogueData(false, "Akhirnye selesai juga."),
            new DialogueData(true, "Kalau gue butuh keterangan lagi, jangan kabur."),
            new DialogueData(false, "Santai aje. Gue tiap hari nongkrong di sini.")
        };

        dialogueManager.SetDialogue(data);
    }
}